/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class KeepAgentSession {
  constructor(scopeConfig?: SessionScopeConfig | undefined | null, rateLimit?: RateLimitOptions | undefined | null, durationHours?: number | undefined | null, policy?: string | undefined | null, secretKey?: string | undefined | null)
  getSessionInfo(): Promise<SessionInfoResult>
  checkOperation(operation: string): Promise<boolean>
  checkEventKind(kind: number): Promise<boolean>
  checkAmount(sats: number): Promise<boolean>
  checkAddress(address: string): Promise<boolean>
  recordRequest(): void
  close(): boolean
  signEvent(kind: number, content: string, tags?: Array<Array<string>> | undefined | null): Promise<SignedEvent>
  signPsbt(psbtBase64: string, network?: string | undefined | null): Promise<string>
  getPublicKey(): Promise<string>
  getBitcoinAddress(network?: string | undefined | null): Promise<string>
}

export declare class RemoteSession {
  static connect(bunkerUrl: string, timeoutSeconds?: number | undefined | null): Promise<RemoteSession>
  signEvent(eventJson: string): Promise<string>
  getPublicKey(): Promise<string>
  nip44Encrypt(pubkey: string, plaintext: string): Promise<string>
  nip44Decrypt(pubkey: string, ciphertext: string): Promise<string>
  ping(): Promise<boolean>
  disconnect(): Promise<void>
}

export declare function createBitcoinScope(): SessionScopeConfig

export declare function createFullScope(): SessionScopeConfig

export declare function createNostrScope(): SessionScopeConfig

export interface RateLimitOptions {
  maxPerMinute?: number
  maxPerHour?: number
  maxPerDay?: number
}

export interface SessionInfoResult {
  sessionId: string
  createdAt: string
  expiresAt: string
  requestsToday: number
  requestsRemaining: number
}

export interface SessionScopeConfig {
  operations?: Array<string>
  eventKinds?: Array<number>
  maxAmountSats?: number
  addressAllowlist?: Array<string>
}

export interface SignedEvent {
  id: string
  pubkey: string
  createdAt: number
  kind: number
  tags: Array<Array<string>>
  content: string
  sig: string
}
